name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 최신 Ubuntu 환경에서 실행

    steps:
      - name: Checkout # 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: Set up Node.js # Node.js 환경 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Node.js 버전, 필요에 따라 조정 (예: '16', '20')

      - name: Install dependencies # 의존성 설치
        run: npm install

      - name: Build # Vite 프로젝트 빌드 (dist 폴더 생성)
        run: npm run build

      - name: Deploy to GitHub Pages # gh-pages 브랜치에 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # dist 폴더의 내용을 배포
          publish_branch: gh-pages # gh-pages 브랜치로 배포 (이 브랜치는 자동으로 생성됨)
          user_name: 'github-actions[bot]' # 커밋 유저 이름
          user_email: 'github-actions[bot]@users.noreply.github.com' # 커밋 유저 이메일